---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ju9mvqk9ihhi/public_html
    - /bin/cp site/index.html $DEPLOYPATH/index.html
    - /bin/mkdir -p $DEPLOYPATH/keepaion.org
    - /bin/cp site/contact.html $DEPLOYPATH/keepaion.org/index.html
